[project]
name = "pac-man"
version = "0.1.0"
description = "pacman game"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mazegenerator",
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "flake8>=7.4.1",
    "mypy>=2.4.0",
]

[tool.uv.sources]
mazegenerator = { path = "mazegenerator-2.1.0-py3-none-any.whl" }
